name = "dom-cash-test"
main = "./.output/server/index.mjs"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["*/15 * * * *"]

[vars]
NUXT_PUBLIC_ENVIRONMENT = "test"

# test
[[d1_databases]]
binding = "DB"
database_name = "dom-test"
database_id = "49fe35ce-d40a-4d38-8f8d-32bd57bb5588"

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "dom-docs-test"


# production
[env.production]
name = "dom-cash"
routes = [
  { pattern = "domcash.ixplo.ai", custom_domain = true }
]

[env.production.triggers]
crons = ["*/15 * * * *"]

[env.production.vars]
NUXT_PUBLIC_ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "dom-prod"
database_id = "5c1aab4d-72d5-4919-a800-274f6e11ed26"

[[env.production.r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "dom-docs-prod"
